// @flow

const types = {
  EDIT_PRODUCER_IS_LOADING: 'EDIT_PRODUCER_IS_LOADING',
  EDIT_PRODUCER_HAS_ERRORED: 'EDIT_PRODUCER_HAS_ERRORED',
  EDIT_PRODUCER_SUCCESS: 'EDIT_PRODUCER_SUCCESS',
}

export default types
