// @flow

const types = {
  FILE_IS_UPLOADING_ADD: 'FILE_IS_UPLOADING_ADD',
  FILE_IS_UPLOADING_REMOVE: 'FILE_IS_UPLOADING_REMOVE',
  FILE_HAS_ERRORED_ADD: 'FILE_HAS_ERRORED_ADD',
  FILE_HAS_ERRORED_REMOVE: 'FILE_HAS_ERRORED_REMOVE',
  FILE_UPLOAD_SUCCESS: 'FILE_UPLOAD_SUCCESS',
}

export default types
