// @flow

const types = {
  PRODUCER_IS_LOADING: 'PRODUCER_IS_LOADING',
  PRODUCER_HAS_ERRORED: 'PRODUCER_HAS_ERRORED',
  PRODUCER_FETCH_DATA_SUCCESS: 'PRODUCER_FETCH_DATA_SUCCESS',
  PRODUCER_INSTAGRAM_FEED_IS_LOADING: 'PRODUCER_INSTAGRAM_FEED_IS_LOADING',
  PRODUCER_CLEAR_STATE: 'PRODUCER_CLEAR_STATE',
  PRODUCER_INSTAGRAM_FEED_HAS_ERRORED: 'PRODUCER_INSTAGRAM_FEED_HAS_ERRORED',
  PRODUCER_FETCH_INSTAGRAM_FEED_SUCCESS: 'PRODUCER_FETCH_INSTAGRAM_FEED_SUCCESS',
  PRODUCER_FETCH_INSTAGRAM_FEED_CLEAR_STATE: 'PRODUCER_FETCH_INSTAGRAM_FEED_CLEAR_STATE',
  PRODUCER_SHARE_PROFILE: 'PRODUCER_SHARE_PROFILE',
}

export default types
