// @flow

const types = {
  CREATE_PRODUCER_IS_LOADING: 'CREATE_PRODUCER_IS_LOADING',
  CREATE_PRODUCER_HAS_ERRORED: 'CREATE_PRODUCER_HAS_ERRORED',
  CREATE_PRODUCER_SUCCESS: 'CREATE_PRODUCER_SUCCESS',
  GEOCODING_ADDRESS_LOOKUP_IS_LOADING: 'GEOCODING_ADDRESS_LOOKUP_IS_LOADING',
  GEOCODING_ADDRESS_LOOKUP_HAS_ERRORED: 'GEOCODING_ADDRESS_LOOKUP_HAS_ERRORED',
  GEOCODING_ADDRESS_LOOKUP_SUCCESS: 'GEOCODING_ADDRESS_LOOKUP_SUCCESS',
  GEOCODING_ADDRESS_LOOKUP_RESET: 'GEOCODING_ADDRESS_LOOKUP_RESET',
}

export default types
