// @flow

const types = {
  CREATE_PRODUCER_IS_LOADING: 'CREATE_PRODUCER_IS_LOADING',
  CREATE_PRODUCER_HAS_ERRORED: 'CREATE_PRODUCER_HAS_ERRORED',
  CREATE_PRODUCER_SUCCESS: 'CREATE_PRODUCER_SUCCESS',
}

export default types
