// @flow

const types = {
  GEOCODING_ADDRESS_LOOKUP_IS_LOADING: 'GEOCODING_ADDRESS_LOOKUP_IS_LOADING',
  GEOCODING_ADDRESS_LOOKUP_HAS_ERRORED: 'GEOCODING_ADDRESS_LOOKUP_HAS_ERRORED',
  GEOCODING_ADDRESS_LOOKUP_SUCCESS: 'GEOCODING_ADDRESS_LOOKUP_SUCCESS',
  GEOCODING_ADDRESS_LOOKUP_RESET: 'GEOCODING_ADDRESS_LOOKUP_RESET',
}

export default types
