// @flow

const types = {
  LOCALITIES_IS_LOADING: 'LOCALITIES_IS_LOADING',
  LOCALITIES_HAS_ERRORED: 'LOCALITIES_HAS_ERRORED',
  LOCALITIES_FETCH_DATA_SUCCESS: 'LOCALITIES_FETCH_DATA_SUCCESS',
}

export default types
