// @flow

const types = {
  CATEGORIES_IS_LOADING: 'CATEGORIES_IS_LOADING',
  CATEGORIES_HAS_ERRORED: 'CATEGORIES_HAS_ERRORED',
  CATEGORIES_FETCH_DATA_SUCCESS: 'CATEGORIES_FETCH_DATA_SUCCESS',
  CATEGORIES_SET_ACTIVE_CATEGORY: 'CATEGORIES_SET_ACTIVE_CATEGORY',
  PRODUCERS_IS_LOADING: 'PRODUCERS_IS_LOADING',
  PRODUCERS_HAS_ERRORED: 'PRODUCERS_HAS_ERRORED',
  PRODUCERS_FETCH_DATA_SUCCESS: 'PRODUCERS_FETCH_DATA_SUCCESS',
  PRODUCERS_FILTER_BY_CATEGORY: 'PRODUCERS_FILTER_BY_CATEGORY',
}

export default types
