// @flow

const types = {
  LOCATION_IS_LOADING: 'LOCATION_IS_LOADING',
  LOCATION_HAS_ERRORED: 'LOCATION_HAS_ERRORED',
  LOCATION_GET_POSITION_SUCCESS: 'LOCATION_GET_POSITION_SUCCESS',
  LOCATION_GET_ADDRESS_FROM_LAT_LNG_SUCCESS: 'LOCATION_GET_ADDRESS_FROM_LAT_LNG_SUCCESS',
}

export default types
