// @flow

const types = {
  SESSION_LOGIN_IS_LOADING: 'SESSION_LOGIN_IS_LOADING',
  SESSION_LOGIN_HAS_ERRORED: 'SESSION_LOGIN_HAS_ERRORED',
  SESSION_LOGIN_SUCCESS: 'SESSION_LOGIN_SUCCESS',
  SESSION_LOGIN_SET_REFERRER_PATH: 'SESSION_LOGIN_SET_REFERRER_PATH',
  SESSION_LOGOUT_SUCCESS: 'SESSION_LOGOUT_SUCCESS',
}

export default types
